name: Create and Publish Docker Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}

jobs:
  build-and-push-image:
    
      runs-on: ubuntu-latest
      permissions: write-all

      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        env:
          BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-build.${{ env.BUILD_NUMBER }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Build Number variable
        shell: bash
        run: gh variable set BUILD_NUMBER -b $(expr ${{ vars.BUILD_NUMBER}} + 1)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
